Add x.com
solorey/Art-Saver pull request #42
Opened 2024-05-24 11:57 UTC by geniuszxy

Fix #41

2024-05-24 13:45 UTC, Houdini111 commented on manifest.json
> +				"*://*.x.com/*"
Does this properly match images found even on the home feed? just `https://x.com`?

2024-05-24 20:47 UTC, solorey requested changes
According to MDN, [document.domain is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/domain)
Instead of `window.document.domain` use `window.location.hostname`

2024-05-25 05:35 UTC, geniuszxy commented on manifest.json
> +				"*://*.x.com/*"
Did you mean downloading images on https://x.com/home?

2024-05-25 13:11 UTC, Mirrorman95 commented
Brilliant! If I'm reading this code correctly, the pull request would allow ArtSaver to download images from X's new URL while still maintaining compatibility with URLs that use the site's old domain name.

2024-05-25 23:34 UTC, solorey commented
Looks good to me.

2024-05-25 23:34 UTC, merged